# Generated by Django 4.2.6 on 2023-10-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('editora', models.CharField(max_length=200, verbose_name='Editora')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('num_pagina', models.CharField(max_length=3, verbose_name='Número de páginas')),
                ('ano_livro', models.CharField(max_length=200, verbose_name='Ano do livro')),
            ],
        ),
    ]
